name: Build Konfig & Samples

on:
  pull_request:
    branches: [ dev-master ]

jobs:
  build-konfig-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradle executable
        run: chmod +x ./gradlew
        working-directory: .
      - name: Building konfig-plugin
        run: ./gradlew :konfig-plugin:build
        working-directory: .

  build-konfig-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradle executable
        run: chmod +x ./gradlew
        working-directory: .
      - name: Building konfig-runtime
        run: ./gradlew :konfig:build
        working-directory: .

  build-sample-android:
    runs-on: ubuntu-latest
    needs: [build-konfig-plugin,build-konfig-runtime]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Generating Sample Apk
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
        working-directory: ./samples/android-sample

  build-sample-browser:
    runs-on: ubuntu-latest
    needs: [build-konfig-plugin,build-konfig-runtime]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Webpacking Browser
        run: |
          chmod +x ./gradlew
          ./gradlew clean webpackDebug
        working-directory: ./samples/browser-sample

  build-sample-desktop:
    runs-on: ubuntu-latest
    needs: [build-konfig-plugin,build-konfig-runtime]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Running App
        run: |
          chmod +x ./gradlew
          ./gradlew runDebug
        working-directory: ./samples/desktop-jvm

  build-sample-mpp-android:
    runs-on: ubuntu-latest
    needs: [build-konfig-plugin,build-konfig-runtime]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: generating apk
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
        working-directory: ./samples/multiplatform-sample

  build-sample-mpp-jvm:
    runs-on: ubuntu-latest
    needs: [build-konfig-plugin,build-konfig-runtime]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Running jvm app
        run: |
          chmod +x ./gradlew
          ./gradlew runJvmDebug
        working-directory: ./samples/multiplatform-sample

  build-sample-mpp-browser:
    needs: [build-konfig-plugin,build-konfig-runtime]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: packing website
        run: |
          chmod +x ./gradlew
          ./gradlew clean webpackJsRelease
        working-directory: ./samples/multiplatform-sample

  build-sample-mm-browser:
    needs: [build-konfig-plugin,build-konfig-runtime]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: packing website
        run: |
          chmod +x ./gradlew
          ./gradlew :todo-browser:clean :todo-browser:webpackRelease
        working-directory: ./samples/multimodule-sample
